services:
  web:
    image: qwitix.azurecr.io/qwitix-web:latest
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    image: qwitix.azurecr.io/qwitix-api:latest
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${SSL_CERT_PATH}:${SSL_CERT_PATH}
      - ${SSL_KEY_PATH}:${SSL_KEY_PATH}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    depends_on:
      - api
      - web
    command: /bin/sh -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

networks:
  app_network:
    driver: bridge
