services:
  web:
    image: ${CONTAINER_NAME}.azurecr.io/qwitix-web:latest
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    image: ${CONTAINER_NAME}.azurecr.io/qwitix-api:latest
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "8080:8080"

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/fullchain.pem:/etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/fullchain.pem
      - /etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/privkey.pem:/etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    depends_on:
      - api
      - web

networks:
  app_network:
    driver: bridge

volumes:
  mongodb-data:
