services:
  web:
    image: qwitix.azurecr.io/qwitix-web:latest
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    image: qwitix.azurecr.io/qwitix-api:latest
    networks:
      - app_network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/fullchain.pem:/etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/fullchain.pem
      - /etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/privkey.pem:/etc/letsencrypt/live/qwitix.germanywestcentral.cloudapp.azure.com/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network
    depends_on:
      - api
      - web

networks:
  app_network:
    driver: bridge
