name: Deploy to Server

on:
  push:
    branches:
      - main

env:
  TARGET_DIR: ./qwitix-infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync files with server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./"
          target: ${{ env.TARGET_DIR }}
          rm: true

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ env.TARGET_DIR }}
            echo "${{ secrets.ENV_FILE }}" > .env
            sudo docker compose pull
            sudo docker compose up -d --build
